server:
  port: 8080
spring:
  datasource:
    name: demo
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.93.132:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml

shiro:
    configLocation: classpath:ehcache-shiro.xml

logging:
  level:
    cn.com.demo: debug
    org.mybatis: info